name: softui_launcher
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  launcher_assist: ^1.1.3
  flutter_statusbarcolor:
  carousel_slider: ^1.4.1
  cupertino_icons: ^0.1.2
  provider: 4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter 

flutter:
  uses-material-design: true
